### ISSUE TITLE
Won't work on first test

### ISSUE THREAD

**Issue by jmconste** [TCWTEAM/Daptcha#1]
I tried to test daptcha on adidas but it gave me an error instead with "localhost is not in the list of supported domains for this sitekey"
I'm currently using a mac and having it already run as an admin
my logs:
`
Miguels-iMac:~ jmpc_$ cd downloads/Daptcha-master
Miguels-iMac:Daptcha-master jmpc_$ sudo python3 server.py
Password:
________                 __         .__            
\______ \ _____  _______/  |_  ____ |  |__ _____   
 |    |  \__  \ \____ \   __\/ ___\|  |  \__  \  
 |    `   \/ __ \|  |_> >  | \  \___|   Y  \/ __ \_
/_______  (____  /   __/|__|  \___  >___|  (____  /
        \/     \/|__|             \/     \/     \/ 

+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
Daptcha BY XO FOR C3WSI
Github Repo https://github.com/TCWTEAM/Daptcha
Twitter @ehxohd
Discord XO#0001
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
DAPTCHA SERVER

running harvester at 127.0.0.1       daptcha.adidas.com:5000
Would you like to clear existing tokens? (y/n): y
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/May/2018 19:46:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/May/2018 19:49:28] "GET / HTTP/1.1" 200 -
settings:
`

**Comment by TCWTEAM** [comment]
issue was a bunch of host entries on adidas.com redirecting to localhost
